apiVersion: spanner.cnrm.cloud.google.com/v1alpha2
kind: SpannerInstance
metadata:
  labels:
    label-one: "value-one"
  name: spannerinstance-sample
  namespace: backend
spec:
  config: regional-us-west1
  displayName: Spanner Instance Sample
  numNodes: 1
