apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"https-ingress-service":"HTTPS","http2-ingress-service":"HTTP"}'
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    operator.istio.io/component: IngressGateway
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.4.0
    release: istio
  name: ingress-service
spec:
  ports:
  - name: status-port-ingress-service
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2-ingress-service
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https-ingress-service
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tls-ingress-service
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
  sessionAffinity: None
  Type: NodePort # typo
