apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: appenvconfigtemplatev2s.appconfigmgr.cft.dev
spec:
  group: appconfigmgr.cft.dev
  names:
    kind: AppEnvConfigTemplateV2
    plural: appenvconfigtemplatev2s
  scope: ""
